#!/usr/bin/env node
// Generates src/environments/environment.prod.ts from the
// EXCHANGE_RATE_API_KEY environment variable.
// Run automatically before every Vercel build via the "build:vercel" script.
// NOTE: environment.ts is committed to git with a placeholder and does NOT
//       need to be generated here.

const fs = require('fs');
const path = require('path');

const apiKey = process.env.EXCHANGE_RATE_API_KEY;
if (!apiKey) {
  console.error(
    'ERROR: EXCHANGE_RATE_API_KEY environment variable is not set.\n' +
    'Add it in Vercel → Project Settings → Environment Variables.',
  );
  process.exit(1);
}

const baseUrl = 'https://v6.exchangerate-api.com/v6';
const envDir  = path.join(__dirname, '..', 'src', 'environments');

fs.mkdirSync(envDir, { recursive: true });

fs.writeFileSync(
  path.join(envDir, 'environment.prod.ts'),
  `// Auto-generated by scripts/set-env.js — do not edit manually.\nexport const environment = {\n  production: true,\n  exchangeRateApiKey: '${apiKey}',\n  exchangeRateApiBaseUrl: '${baseUrl}',\n};\n`,
);

console.log('✔  environment.prod.ts generated successfully.');
